version: '3'

tasks:
  build:
    desc: Build the Bitwarden Secrets Manager Docker image
    cmds:
      - docker-compose build
  
  run:
    desc: Run the Bitwarden Secrets Manager
    cmds:
      - docker-compose up app
  
  cli:
    desc: Run the Bitwarden CLI tool with custom arguments
    cmds:
      - docker-compose run --rm cli {{.CLI_ARGS}}
    requires:
      vars: [CLI_ARGS]
  
  create-secret:
    desc: Create a new secret in Bitwarden
    cmds:
      - docker-compose run --rm cli create-secret {{.name}} {{.value}} --note "{{.note}}"
    vars:
      name: '{{default "key" .name}}'
      value: '{{default "value" .value}}'
      note: '{{default "nota" .note}}'
  
  list-secrets:
    desc: List all secrets in Bitwarden
    cmds:
      - docker-compose run --rm cli list-secrets

  get-secret:
    desc: Get a specific secret from Bitwarden
    cmds:
      - docker-compose run --rm cli get-secret {{.key}}
    vars:
      key: '{{default "KEY_NAME" .key}}'
    
  sync-secrets:
    desc: Sync all secrets to local file
    cmds:
      - docker-compose run --rm cli sync-secrets
  
  convert-to-env:
    desc: Convert secrets from JSON to .env format
    cmds:
      - docker-compose run --rm cli convert-to-env --json-file {{.json_file}} --env-file {{.env_file}}
    vars:
      json_file: '{{default "data/secrets.json" .json_file}}'
      env_file: '{{default "data/secrets1.env" .env_file}}'
  
  convert-to-json:
    desc: Convert secrets from .env to JSON format
    cmds:
      - docker-compose run --rm cli convert-to-json --env-file {{.env_file}} --json-file {{.json_file}}
    vars:
      env_file: '{{default "data/secrets.env" .env_file}}'
      json_file: '{{default "data/secrets1.json" .json_file}}'
