version: '3'

tasks:
  build:
    desc: Build the Bitwarden Secrets Manager Docker image
    cmds:
      - docker-compose build
  
  run:
    desc: Run the Bitwarden Secrets Manager
    cmds:
      - docker-compose up app
  
  cli:
    desc: Run the Bitwarden CLI tool with custom arguments
    cmds:
      - docker-compose run --rm cli {{.CLI_ARGS}}
    requires:
      vars: [CLI_ARGS]
  
  create-secret:
    desc: Create a new secret in Bitwarden
    cmds:
      - docker-compose run --rm cli create-secret {{.name}} {{.value}} --note "{{.note}}"
    vars:
      name: '{{default "key" .name}}'
      value: '{{default "value" .value}}'
      note: '{{default "nota" .note}}'
  
  list-secrets:
    desc: List all secrets in Bitwarden
    cmds:
      - docker-compose run --rm cli list-secrets

  get-secret:
    desc: Get a specific secret from Bitwarden
    cmds:
      - docker-compose run --rm cli get-secret {{.key}}
    vars:
      key: '{{default "KEY_NAME" .key}}'
    
  sync-secrets:
    desc: Sync all secrets to local file
    cmds:
      - docker-compose run --rm cli sync-secrets
